---
title: "Juegos de rol para design thinking en enseñanza basada en proyecto"
author: "JJ Merelo"
date: "`r Sys.Date()`"
output: word_document
abstract: |
  La enseñanza basada en proyecto se debe basar en aprender las diferentes metodologías aplicables en diferentes fases del desarrollo del mismo. En la fase inicial de diseño del proyecto, *design thinking* es una de las metodologías más aceptadas. Para aprender esa metodología se ha diseñado un juego de rol y se ha hecho una experiencia en la asignatura Infraestructura Virtual del grado en Ingeniería Informática. En este trabajo trataremos de exponer en qué ha consistido la experiencia y los resultados, todavía iniciales, obtenidos.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducción

 Uno de los problemas principales en la asignatura que imparto en cuarto de Informática es el tratar de convencer a los estudiantes que lo que sea que aprendan va a serles útil en su vida profesional, e incluso en el resto de las asignaturas o el trabajo fin de grado.

Que eso suceda así es consecuencia de muchas cosas, muchas de las cuales denuncié en esta carta abierta, pero una cosa es denunciar y otra dar trigo, así que hay que poner algo de mi parte para poder motivar, pero lo principal es que entiendan la realidad de los contenidos que se tratan de impartir.
Un poco de contexto

En la asignatura uso aprendizaje basado en proyecto y evaluación formativa; esencialmente los estudiantes tienen que ir elaborando un proyecto propio, alcanzando diferentes objetivos a lo largo del curso; la retroalimentación del profesor y de otros estudiantes les debe ayudar a alcanzarlos.

El problema es que en cada uno de esos objetivos, la preocupación principal del estudiante es "qué hay que poner ahí" y no qué conceptos hay que entender para poder superar el objetivo. Y es así porque es casi imposible transmitir la idea de que esos conceptos son reales, útiles y basados en las mejores prácticas de la industria. La realidad del proyecto es lo más complicado de transmitir, y salvo que se produzca una epifanía, prácticamente imposible de enseñar. Y eso lleva al fracaso.

Empezando por el primer objetivo, en realidad objetivo 0, que es que entiendan que la ingeniería resuelve problemas, y que para poder cerciorarse de que efectivamente se ha resuelto el problema, el estudiante debe estar familiarizado con el mismo, debe ser un problema propio o de algún familiar cercano, o uno en el que realmente tenga interés. Si no tiene interés, o, volviendo al principio, se convierte en "algo que poner ahí pero que no tiene nada que ver con nada" en vez de un problema real que hay que modelizar y posteriormente tratar de abordar mediante un programa informático, no sirve absolutamente de nada.
Introduciendo Design Thinking

Design thinking es una metodología para desarrollar productos desde cero. En el objetivo 0 se les anima a que conozcan y usen esa metodología para definir el problema con el que se va a trabajar, a través de la fase inicial, de empatía, que es fundamental para identificar al cliente y qué es lo que necesita de la aplicación.

Por supuesto, esos enlaces no le sirven de nada al estudiante. No les importa mucho formular el problema o aprender a formularlo. Al final, algunos acaban superando el objetivo 0 a base de múltiples revisiones (de eso va la evaluación formativa) y explicaciones por parte mía; algunos simplemente lo dejan o no llegan ni siquiera a entregar este objetivo. Pero todo ello acaba siendo poco práctico, y sobre todo, no proporciona esa epifanía que hace que el estudiante entienda la realidad del problema, y por tanto del proyecto, y por tanto del valor que le puede aportar la asignatura.

En algunos casos, además, hay estudiantes que son incapaces de superar ese primer objetivo simplemente porque son incapaces de pensar en un problema a resolver, o de formular un problema que sea mínimamente real y por tanto la base para la construcción de una aplicación.
Introduciendo un juego de rol

Empatizar es literalmente ponerse en los zapatos de otra persona, el cliente en este caso, que tiene un problema, y entender cuál es el problema. La metodología de design thinking identifica muy bien la clave de diseñar un producto con éxito: si no entiendes a tu cliente, es imposible. Pero desde el punto de vista informático, si no lo entiendes no puedes formular correctamente historias de usuario, y no puedes crear a partir de ellas tests que efectivamente comprueben que se ha resuelto el problema.

Desde el punto de vista de la asignatura y de la enseñanza, empatizar debería proporcionar esa epifanía que vamos buscando. Al ponerte en los zapatos de tu cliente, entiendes que el problema que tiene es real y vas a intentar hacer lo posible para solucionarlo.

Con esos ejes, la empatía y la realidad, me he puesto a diseñar un mini-juego de rol que ayude al estudiante a formular el problema que va a tratar en la asignatura, usando fichas diseñadas ex profeso.

En este juego de rol, hay un cliente que tiene un problema y un dev que le quiere ayudar a desarrollar ese problema.

El cliente usará esta ficha para escribir, a mano, cuál es su problema. De esta forma se anima al estudiante a esforzarse en formular el problema de forma que lo entienda otra persona, pero a la vez asumirá el rol del cliente, de forma que tiene que empatizar con él para poder saber qué es lo que quiere. A la vez, separamos el problema de la posible solución (algo que es muy complicado hacer entender también), para que se centren en qué es lo que hay que solucionar, no en la solución.

El entrevistador/desarrollador/a usará esta ficha, para resumir cuál es el problema que se quiere resolver; al confrontar el problema con otra persona (aparte del profesor) el estudiante tendrá que esforzarse en convencer que realmente se trata de un problema. El dev o entrevistador, a la vez, podrá darle una retroalimentación temprana de si es un problema o no que pueda resolverse con un programa en la nube (en una segunda fase del juego).

Como hemos comentado, también hay casos en que el estudiante no sabe formular ningún problema. En ese caso, el entrevistador le ayudará a encontrar alguno usando esta ficha, de forma que pueda más o menos sacar alguna cosa que puedan resolver en la asignatura.

Las fichas se imprimirán en papel, y se le entregarán a cada uno de los estudiantes, que tendrán que escribir preferiblemente en bolígrafo. Una vez escrito, tendrán que entregar el objetivo de la forma habitual. 

## Desarrollo del juego

Los estudiantes se organizan en parejas, y deciden quién va a ser
estudiante A y estudiante B. El estudiante A *planteará el problema* y
el estudiante B *tratará de comprenderlo y a continuación, lo resumirá*.

<table>
  <thead>
    <th> Estudiante A </th><th> Estudiante B </th>
  </thead>

  <tbody>
<tr><td colspan="2"> <strong>5 minutos</strong> Los
estudiantes, organizados por parejas, tienen 5 minutos para escribir,
preferiblemente en papel y con bolígrafo, los problemas que conocen y
que piensan que pueden abordar mediante un programa. El énfasis es en
que piensen en <em>los problemas</em>, no la solución. </td></tr>
<tr><td> <strong>Opción 1</strong> <strong>15 minutos</strong> Asume
el rol de la persona <em>que tiene el problema</em>; le contará
primero quién o qué es ("Soy un gerente de una empresa de envase de
frutas", "Soy un estudiante que quiere comer sano", "Soy una persona
mayor que quiere organizar mejor el tiempo de ejercicio") qué es lo
que ocurre, qué es lo que querría hacer mejor, o hacer, o hacer de
otra manera, usando si es necesario papel y lápiz para mostrarle a B
como hace las cosas y qué problema hay con las mismas. Tomará notas de
las preguntas adicionales o con las aclaraciones que tenga que hacer
sobre el problema inicial. Al final de este proceso, se invertirán los
roles de estudiante A y estudiante B.</td>
<td>Es un entrevistador que
quiere entender qué necesita: tiene que empezar por preguntarle "¿En
qué puedo ayudarte?" o "¿Qué problema tenemos entremanos?". A
continuación, le hará las preguntas necesarias para entender bien qué
es lo que necesita, absteniéndose de formular ningún tipo de solución
posible y tomará notas. Al final de los 15 minutos, consultando si es
necesario las notas, le resumirá al estudiante A (el <em>cliente</em>)
lo que ha entendido. También le dará una valoración de si entiende que
se podría resolver dentro de una asignatura como IV, de
infraestructura virtual. Al final de este proceso, se invertirán los
roles de estudiante A y estudiante B.  </td> </tr>

<tr>
    <td><strong>Opción 2</strong> <strong>15 minutos</strong>
Puede
    que no haya tenido tiempo de formular ninguna idea en los 5
    minutos anteriores, o no tiene ninguna idea clara. Al final de los
    15 minutos, con la ayuda del estudiante B, tendrá que plantear el
    problema que luego enviará para el objetivo 0.
    </td>

   <td>Tendrá que intentar ayudarle
a formular ese problema, haciéndole preguntas como <ol> <li>¿Alguna
afición podría mejorar con ayuda de algún programa?</li> <li> ¿Alguna
tarea doméstica o el conjunto de las mismas en su vivienda podrían ser
algún problema? ¿O la organización de las mismas?</li> <li>¿Alguna
preocupación social o política podría ser un problema mejorable con
alguna aplicación?</li> <li> ¿Hay algún dato que se pueda procesar a
partir de fuentes poco estructuradas? ¿Ofertas de algo?  ¿Información
de alguna página de una institución?</li> </ol> Eventualmente tendrán
que intentar entre los dos formular el problema que el estudiante A
podrá plantear en la asignatura.  </td>
</tr>

<tr>
    <td
colspan="2"><strong>15 minutos</strong>Estudiante A será ahora
estudiante B, y viceversa, y llevarán a cabo una de las dos opciones
anteriores.
    </td>
</tr>

<tr>
     <td colspan="2"><em>Validación</em>
<strong>10 minutos</strong>: se establacen nuevas parejas, y una vez más
estudiante A volverá a asumir el rol del posible cliente y contar qué
problema tiene con las modificaciones que haya hecho en la interacción
anterior; una vez más el estudiante B será entrevistador, hará
preguntas y solicitará aclaraciones, y al final validará (o no) el
problema planteado como un problema que podría ser válido para la
asignatura. Si el estudiante B no valida el problema para la
     asignatura, se volverá al paso anterior de formulación del
     problema en el tiempo que permita la clase, con la temporización
     necesaria y creando parejas entre las personas que no se hayan
     validado. El estudiante B le entregará al A la ficha con lo que
     ha impedido la validación, para que lleve a cabo otra iteración
     del mismo o plantee un problema diferente.
     </td>
</tr>

<tr><td colspan="2"> <em>Puesta en común</em>: la clase dirá qué ha
    aprendido de la experiencia, y sugerirá mejoras para iteraciones
    sucesivas.  </td> </tr>

</tbody>
</table>
